services:
  server:
    image: comfyui
    ports:
      - ${COMFYUI_PORT}:8188
      - ${JUPYTER_PORT}:8888
    volumes:
        - type: volume
          source: comfyui_models
          target: /workspace/ComfyUI/models
        - type: volume
          source: comfyui_custom_nodes
          target: /workspace/ComfyUI/custom_nodes
        - type: volume
          source: comfyui_user
          target: /workspace/ComfyUI/user
        - ./output:/workspace/ComfyUI/output
        - ./models:/workspace/importModels
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
     - COMFYUI_PORT=${COMFYUI_PORT}
     - JUPYTER_PORT=${JUPYTER_PORT}
     - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    build:
      context: .
volumes:
    comfyui_models:
        name: comfyui_models
    comfyui_custom_nodes:
        name: comfyui_custom_nodes
    comfyui_user:
        name: comfyui_user